pub mod brain;
pub mod candle_vllm;
pub mod client;
pub mod config;
pub mod config_store;
pub mod daemon;
pub mod e2e;
pub mod domains;
pub mod error;
pub mod factories;
pub mod guardrails;
pub mod interfaces;
pub mod plugins;
pub mod providers;
pub mod reminders;
pub mod scheduler;
pub mod services;
pub mod sqlcipher;
pub mod tools;
pub mod tor_spike;
pub mod ui;
pub mod vault;

pub type Result<T> = std::result::Result<T, error::ButterflyBotError>;

pub use crate::client::ButterflyBot;
pub use crate::config::Config;
pub use crate::error::ButterflyBotError;
pub use crate::interfaces::providers::{ImageData, ImageInput};
pub use crate::services::query::{OutputFormat, ProcessOptions, ProcessResult, UserInput};
